version: "3.7"

services:
  forticlient:
    build:
      context: .
      dockerfile: Dockerfile
    image: hybirdcorp/docker-forticlient
    environment:
      - VPNADDR=host:port
      - VPNUSER=me@domain
      - VPNPASS=secret
      - VPNTIMEOUT=${VPNTIMEOUT:-10}
    network_mode: "host"
    privileged: true